name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Main Test
      id: main-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Main Test
        setup-command: 'python -m pip install --upgrade pip pip install pytest  #
          Download hidden tests from the private repo curl -sSL -H "Authorization:
          token ${{ secrets.HIDDEN_TESTS_TOKEN }}" \   https://raw.githubusercontent.com/FederatedLearningAalto/HiddenTests/main/assignment_0/test_hidden.py
          \   -o test_hidden.pypython -m pip install --upgrade pip pip install pytest  #
          Download hidden tests from the private repo curl -sSL -H "Authorization:
          token ${{ secrets.HIDDEN_TESTS_TOKEN }}" \   https://raw.githubusercontent.com/FederatedLearningAalto/HiddenTests/main/assignment_0/test_hidden.py
          \   -o test_hidden.pypython -m pip install --upgrade pip pip install pytest  #
          Download hidden tests from the private repo curl -sSL -H "Authorization:
          token ${{ secrets.HIDDEN_TESTS_TOKEN }}" \   https://raw.githubusercontent.com/FederatedLearningAalto/HiddenTests/main/assignment_0/test_hidden.py
          \   -o test_hidden.py'
        command: python -m pytest -q test_hidden.py
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MAIN-TEST_RESULTS: "${{steps.main-test.outputs.result}}"
      with:
        runners: main-test
